In [1]:
import numpy as np
import pandas as pd

In [2]:
# Step 1 Collect Data
X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
            [1],
            [1],
            [0]])

In [4]:
X.shape

(4, 3)

In [7]:
np.random.random((4,3))

array([[ 0.09386728,  0.14037602,  0.63780947],
       [ 0.62929599,  0.46380561,  0.81695685],
       [ 0.35691301,  0.34185943,  0.4058522 ],
       [ 0.14658958,  0.41323816,  0.50315074]])

In [13]:
np.random.normal(size=(4,3))

array([[-0.04161039, -0.41140058, -0.79603132],
       [-0.5276958 , -0.8161976 ,  0.45305892],
       [-1.73621021, -1.49959318, -1.50237487],
       [-0.30250839,  0.25305523, -0.84207471]])

In [26]:
np.random.seed(7)
syn0 = np.random.random((3,4)) - 1
syn1 = np.random.random((4,1)) -1
syn0, syn1

(array([[-0.92369171, -0.22008121, -0.56159077, -0.27653482],
        [-0.02201049, -0.46150413, -0.49887954, -0.92794887],
        [-0.73156102, -0.5001175 , -0.32077   , -0.19626096]]),
 array([[-0.61905887],
        [-0.93406365],
        [-0.7118544 ],
        [-0.09040647]]))

In [39]:
import numpy as np

# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))
    
# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])
    
# output dataset            
y = np.array([[0,0,1,1]]).T

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1

for iter in xrange(10000):

    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))

    # how much did we miss?
    l1_error = y - l1
    print l1_error
    print nonlin(l1,True)
    
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)
    print l1_delta

    # update weights
    syn0 += np.dot(l0.T,l1_delta)
    break

print "Output After Training:"
print l1


[[-0.2689864 ]
 [-0.36375058]
 [ 0.76237183]
 [ 0.6737243 ]]
[[ 0.19663272]
 [ 0.23143609]
 [ 0.18116102]
 [ 0.21981987]]
[[-0.05289153]
 [-0.08418501]
 [ 0.13811206]
 [ 0.14809799]]
Output After Training:
[[ 0.2689864 ]
 [ 0.36375058]
 [ 0.23762817]
 [ 0.3262757 ]]
